dogcollecter/dogcollecter/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

dogcollecter/main_app/urls.py
from django.urls import path
from . import views 

urlpatterns = [
  path('', views.Home.as_view(), name='home'),
  path('about/', views.about, name='about'),
  path('dogs/', views.dog_index, name='dog-index'),
  path('dogs/<int:dog_id>/', views.dog_detail, name='dog-detail'),
  path('dogs/create/', views.DogCreate.as_view(), name='dog-create'),
  path('dogs/<int:pk>/update', views.DogUpdate.as_view(), name='dog-update'),
  path('dogs/<int:pk>/delete', views.DogDelete.as_view(), name='dog-delete'),
  path(
        'dogs/<int:dog_id>/add-feeding/', 
        views.add_feeding, 
        name='add-feeding'
    ),
  path('accounts/signup/', views.signup, name='signup'),
]

dogcollecter/main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import User

MEALS = (
    ('B', 'Breakfast'),
    ('L', 'Lunch'),
    ('D', 'Dinner')
)

class Dog(models.Model):
    name = models.CharField(max_length=100)
    breed = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    age = models.IntegerField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("dog-detail", kwargs={"dog_id": self.id})
    
class Feeding(models.Model):
    date = models.DateField('Feeding date')
    meal = models.CharField(
        max_length=1,
        choices=MEALS,
        default=MEALS[0][0]
    )
    dog = models.ForeignKey(Dog, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.get_meal_display()} on {self.date}"
    
    class Meta:
        ordering = ['-date']  # This line makes the newest feedings appear first

dogcollecter/main_app/forms.py
from django import forms
from .models import Feeding

class FeedingForm(forms.ModelForm):
    class Meta:
        model = Feeding
        fields = ['date', 'meal']
        widgets = {
            'date': forms.DateInput(
                format=('%Y-%m-%d'),
                attrs={
                    'placeholder': 'Select a date',
                    'type': 'date'
                }
            ),
        }

dogcollecter/main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Dog
from .forms import FeedingForm
from django.contrib.auth.views import LoginView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

class Home(LoginView):
    template_name = 'home.html'

def about(request):
    return render(request, 'about.html')

@login_required
def dog_index(request):
    dogs = Dog.objects.filter(user=request.user)
    return render(request, 'dogs/index.html',{'dogs': dogs})

@login_required
def dog_detail(request, dog_id):
    dog = Dog.objects.get(id=dog_id)
    feeding_form = FeedingForm()
    return render(request, 'dogs/detail.html', {'dog': dog, 'feeding_form': feeding_form})

class DogCreate(LoginRequiredMixin, CreateView):
    model = Dog
    fields = ['name', 'breed', 'description', 'age']

    def form_valid(self, form):
        form.instance.user = self.request.user 
        return super().form_valid(form)

class DogUpdate(LoginRequiredMixin, UpdateView):
    model = Dog
    fields = ['breed', 'description', 'age']

class DogDelete(LoginRequiredMixin, DeleteView):
    model = Dog
    success_url = '/dogs/'

@login_required
def add_feeding(request, dog_id):
    form = FeedingForm(request.POST)
    if form.is_valid():

        new_feeding = form.save(commit=False)
        new_feeding.dog_id = dog_id
        new_feeding.save()
    return redirect('dog-detail', dog_id=dog_id)

def signup(request):
    error_message = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('cat-index')
        else:
            error_message = 'Invalid sign up - try again'
    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'signup.html', context)

dogcollecter/main_app/templates/about.html
{% extends 'base.html' %} 
{% block content %}
<h1>About the Dog Collector</h1>
<hr />
<p class="page-content">
  I like long romantic walks down the produce aisle. Also, I am currently job
  seeking!
</p>
{% endblock %}

dogcollecter/main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="shortcut icon" type="image/png" href="{% static "images/pawlogo.svg" %}" />
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <title>Dog Collector</title>
    {% block head %} 
    {% endblock %}
  </head>
  <body>
    <header>
      <div class="header-logo-container">
        <a href="/">
          <img src="{% static "images/header-logo.svg" %}" alt="The Dog Collector Logo" />
        </a>
      </div>
      <nav>
        <ul>
          {% if user.is_authenticated %}
            <li><a href="{% url 'dog-index' %}">All Dogs</a></li>
            <li><a href="{% url 'dog-create' %}">Add a Dog</a></li>
            <li><a href="{% url 'about' %}">About</a></li>
            <li>
              <form id="logout-form" method="post" action="{% url 'logout' %}">
                {% csrf_token %}
                <button type="submit">Log out</button>
              </form>
            </li>
          {% else %}
            <li><a href="{% url 'about' %}">About</a></li>
            <li><a href="{% url 'home' %}">Login</a></li>
            <li><a href="{% url 'signup' %}">Sign Up</a></li>
          {% endif %}
        </ul>
      </nav>
    </header>
    <main>
     {% block content %} 
     {% endblock %}
     </main>
  </body>
</html>

dogcollecter/main_app/templates/dogs/detail.html
{% extends 'base.html' %} {% load static %} {% block head %}
<link rel="stylesheet" href="{% static 'css/dogs/dog-detail.css' %}" />
{% endblock %} {% block content %}
<section class="dog-container">
  <div class="cat-img">
    <img src="{% static 'images/sk8r-boi-cat.svg' %}" alt="A skater boy dog" />
  </div>
  <div class="cat-details">
    <h1>{{ dog.name }}</h1>
    {% if dog.age > 0 %}
    <h2>A {{ dog.age }} year old {{ dog.breed }}</h2>
    {% else %}
    <h2>A {{ dog.breed }} puppy.</h2>
    {% endif %}
    <p>{{ dog.description }}</p>
    <div class="cat-actions">
      <a href="{% url 'dog-update' dog.id %}" class="btn warn">Edit</a>
      <a href="{% url 'dog-delete' dog.id %}" class="btn danger">Delete</a>
    </div>
    <!-- Existing cat-container above -->
    <div class="feedings-toy-container">
      <section class="feedings">
        <div class="subsection-title">
          <h2>Feedings</h2>
          <img
            src="{% static 'images/cat-cone.svg' %}"
            alt="An ice cream cone cat"
          />
          <img
            src="{% static 'images/cat-onigiri.svg' %}"
            alt="A cat as onigiri"
          />
          <img
            src="{% static 'images/kitty-kabob.svg' %}"
            alt="A kabob of kittens"
          />
        </div>
        <h3>Past Feedings</h3>
        {% if dog.feeding_set.all.count %}
        <table>
          <thead>
            <tr>
              <th>Date</th>
              <th>Meal</th>
            </tr>
          </thead>
          <tbody>
            {% for feeding in dog.feeding_set.all %}
            <tr>
              <td>{{feeding.date}}</td>
              <td>{{feeding.get_meal_display}}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
        {% else %}
        <div class="subsection-content">
          <p>⚠️ {{dog.name}} has not been fed!</p>
        </div>
        {% endif %}
        <h3>Add a Feeding</h3>
        <form
          action="{% url 'add-feeding' dog.id %}"
          method="post"
          class="subsection-content"
          autocomplete="off"
        >
          {% csrf_token %} {{ feeding_form.as_p }}
          <button type="submit" class="btn submit">Add Feeding</button>
        </form>
      </section>
    </div>

    {% endblock %}
  </div>
</section>

dogcollecter/main_app/templates/dogs/index.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/dogs/dog-index.css' %}"/>
{% endblock %} 
{% block content %}

<section class="page-header">
  <h1>Dog List</h1>
  <img src="{% static 'images/cool-cat.svg' %}" alt="A cool dog" />
  <img src="{% static 'images/happy-cat.svg' %}" alt="A happy dog" />
  <img src="{% static 'images/teacup-cat.svg' %}" alt="A dog in a teacup" />
  <img src="{% static 'images/cat-in-box.svg' %}" alt="A dog in a box" />
</section>

<section class="card-container">
  {% for dog in dogs %}
    <div class="card">
        <a href="{% url 'dog-detail' dog.id %}">
      <div class="card-content">
        <div class="card-img-container">
          <img
            src="{% static 'images/sk8r-boi-cat.svg' %}"
            alt="A skater boy dog"
          />
        </div>
        <h2 class="card-title">{{ dog.name }}</h2>
        {% if dog.age > 0 %}
        <p>A {{ dog.age }} year old {{ dog.breed }}</p>
        {% else %}
        <p>A {{ dog.breed }} puppy.</p>
        {% endif %}
        <p><small>{{ dog.description }}</small></p>
      </div>
    </a>
    </div>
  {% endfor %}
</section>

{% endblock %}

dogcollecter/main_app/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/home.css' %}" />
{% endblock %}
{% block content %}

<section class="logo-container">
  <div class="dog-container">
    <img src="{% static 'images/splash.svg' %}" alt="The Dog Collector Dog" />
  </div>
  <img src="{% static 'images/logotype.svg' %}" alt="Text reads: Dog Collector" />
</section>
{% if not user.is_authenticated %}
  <section>
    <form action="{% url 'home' %}" method="post" class="login">
      <h1>Login</h1>
      {% csrf_token %} {{ form.as_p }}
      <input type="hidden" name="next" value="{{ next }}" />
      <button type="submit" class="btn submit">Login</button>
    </form>
  </section>
{% endif %}

{% endblock %}

dogcollecter/main_app/templates/main_app/dog_confirm_delete.html
{% extends 'base.html' %}  
{% load static %} 
{% block content %}

<div class="page-header">
  <h1>Delete Dog?</h1>
  <img src="{% static 'images/nerd-cat.svg' %}" alt="A cat using a computer" />
</div>

<h2>Are you sure you want to delete {{ dog.name }}?</h2>

<form action="" method="post" class="form">
  {% csrf_token %}
  <a href="{% url 'dog-detail' dog.id %}" class="btn secondary">Cancel</a>
  <button type="submit" class="btn danger">Yes - Delete!</button>
</form>

{% endblock %}

dogcollecter/main_app/templates/main_app/dog_form.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/form.css' %}" />
{% endblock %} 
{% block content %}

<div class="page-header">
    {% if dog %}
      <h1>Edit {{ dog.name }}</h1>
    {% else %}
      <h1>Add a Dog</h1>
    {% endif %}
  </div>

<form action="" method="post" class="form-container">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <button type="submit" class="btn submit">Submit!</button>
</form>

{% endblock %}

dogcollecter/main_app/templates/signup.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/form.css' %}" />
{% endblock %} 
{% block content %}
<div class="page-header">
  <h1>Sign Up</h1>
  <img src="{% static 'images/nerd-cat.svg' %}" alt="A cat using a computer" />
</div>
{% if error_message %}
  <p class="red-text">{{ error_message }}</p>
{% endif %}
<form action="" method="post" class="form-container" autocomplete="off">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <button type="submit" class="btn submit">Submit!</button>
</form>

{% endblock %}